[package]
name = "proto-definitions"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
description.workspace = true
homepage.workspace = true

[dependencies]
prost = "0.14.1"

[dev-dependencies]
prost-build = "0.14.1"
