[workspace]
resolver = "2"
members = ["aggregator", "mastodon"]

[workspace.dependencies]
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Joel DSouza <joeldsouzax@gmail.com>"]
repository = "https://github.com/joeldsouzax/social-aggregator"

[workspace.metadata.crane]
name = "social-aggregator"
