[package]
name = "mastodon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.100"
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
