name: udpate dependencies
on:
  schedule:
    - cron: "0 9 * * MON"
  workflow_dispatch:
jobs:
  checks:
    name: Update Dependencies and Create PR
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-dept: 0
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: build-${{ runner.os }}-${{ hashFiles('Cargo.toml', 'flake.nix', 'flake.lock', 'Cargo.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: cache-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

      - name: Enter Nix Shell and Update Dependencies
        run: |
          nix develop --command bash -c "
            set -e # Exit immediately if a command exits with a non-zero status.
            echo 'Updating Nix flake...'
            nix flake update
            echo 'Updating cargo lockfile...'
            cargo update
            echo 'Generating cargo-hakari workspace...'
            cargo-hakari generate --diff # Adding --diff to see changes, though not strictly necessary for the script's logic
            echo 'Dependency update process complete.'
          "
      - name: Create Pull Request if changes exist
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT_FOR_PRS }}
          commit-message: "chore: update dependencies"
          title: "Update Nix and Rust Dependencies"
          body: |
            Automated weekly dependency update.
            Please review the changes.
            - Nix flake updated
            - Cargo dependencies upgraded/updated
            - Cargo Hakari workspace regenerated
          branch: "chore/auto-dependency-updates"
          delete-branch: true
          labels: |
            dependencies
            automated pull request
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
